fs_db.media:
  image: tianon/true
  volumes:
    - ./mysql_media-autoload:/docker-entrypoint-initdb.d:ro
    - ./mysql_media-datadir:/var/lib/mysql:z
    - ./mysql_media-shr:/shr:z
    - ./mysql_media-conf.d:/etc/mysql/conf.d:z

fs_as:
  image: tianon/true
  volumes:
    - ./srv/media:/opt/data/media
    - ./srv/log:/opt/jboss/wildfly/standalone/log

db.media:
  image: mysql:5.6
  env_file: env/.env-db
  volumes_from:
    - fs_db.media

mediaserver:
  #build: ./wildfly-custom
  image: ${IMAGE}:${TAG}
  env_file: .env
  environment:
   - VIRTUAL_HOST=beta-media.dina-web.net
   - VIRTUAL_PORT=8080
  volumes_from:
    - fs_as
  links:
    - db.media:dbmedia
